### ISSUE TITLE
Review Improvements, Iteration 1

### ISSUE THREAD

**Issue by gabestein** [pubpub/roadmap-repo#10]
**Review Improvements**
Pub Admins can invite reviewers, choose review types, and submit structured review feedback.

**Comment by Robert-Roth** [comment]
Will this include email notifications about comments and other comment management tools? You linked that line of our wishlist to issue #10 so I just want to make sure that's all included under review improvements

**Comment by gabestein** [comment]
Not exactly, no. As I commented in the wishlist, that was a giant chunk of ideas that's hard to think of as one feature — as such, the solutions for are going to be folded into other places (and some, like comment links, have already been done).

I linked here from that item because I suspect this is where we'll do some notification work as well as some work to allow replying without being on the Pub. But it's also a little too early to know, as we haven't begun scoping this yet. Of course, we'll take the ideas into account when we do, and rest assured, the desires around commenting haven't been lost — they're in a bunch of different places.
