### ISSUE TITLE
Layouts, Iteration 1

### ISSUE THREAD

**Issue by gabestein** [pubpub/roadmap-repo#6]
**What**
Allows users to select from a gallery of custom "chrome" layouts for header, footer, and potentially sidebars.

**Why?**
Allows more types of communities to use PubPub by allowing them to adapt it better to their needs.

**Prior Discussion**
https://notes.knowledgefutures.org/pub/0mm44rx1/draft

**Who?**
Arcadia, eLife, Sonic Scope, JTOE, etc...

**Comment by Robert-Roth** [comment]
Is there any plan to natively integrate feedback forms and a Twitter feed, and does this also include changing what is viewable by users who aren't logged in (i.e., users who aren't logged in shouldn't see 'Dashboard' or 'Create pub')? Making sure that comment was captured here

**Comment by gabestein** [comment]
Content in the header: yes, although that'll be on a layout-by-layout basis, not a built in feature (that is, we'll be able to build different things into different layouts).

Blocks: Likely not in the first iteration, no. We're thinking about blocks for iteration 2.
