### ISSUE TITLE
Layouts, Iteration 2

### ISSUE THREAD

**Issue by gabestein** [pubpub/roadmap-repo#7]
**What?**
- Replace page editor with Pub editor
- Customization of Pub blocks

**Comment by Robert-Roth** [comment]
Would this also include a table of contents and a save and preview changes (without publishing) option?

**Comment by gabestein** [comment]
Save/Preview: the idea in replacing the page editor with the pub editor in the original comment is to have a similar draft/release model to Pubs so you can make changes without publishing.

TOC: It's definitely on the table for it. We haven't started scoping yet, though, so I don't know what we'll be able to fold in yet.
